#######################
# Theme Customization #
#######################

title: DRL_in_CV          # appears in the header and the HTML <title> tag
author: Aditya Ganeshan     # appears in an HTML <meta> tag, as well as feed.xml
description: >           # appears in an HTML <meta> tag, as well as feed.xml
  A site for Deep reinforcement learning in Computer Vision 
slogan: Nil        # appears in the header, alongside the title
avatar: /i/avatar_3.png    # appears as portrait in the header
banner: /i/mountains.svg # appears as background in the header
url: http://jekyllrb.com # used by plugins to generate feed.xml and sitemap.xml
baseurl: '/DRL_in_CV/'              # prepended to all absolute filepaths
repo: https://github.com//rlue.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Course
    url: /
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Posts
    url: /projects
    icon: /i/icons.svg#portfolio
  - name: Papers
    url: /DRL_in_CV_Papers/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: Contact
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
projects:
  - title: Solana
    teaser: A responsive blog template written in Sass and vanilla JavaScript.
    url: https://github.com/rlue/solana
    role: Creator
    category: Frontend Dev
  - title: Cortana
    teaser: A talking robot. Now available on Google Play?
    url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
    role: Core Team
    category: NLP
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 15
 