#######################
# Theme Customization #
#######################

title: DRL_in_CV          # appears in the header and the HTML <title> tag
author: Aditya Ganeshan     # appears in an HTML <meta> tag, as well as feed.xml
description: >           # appears in an HTML <meta> tag, as well as feed.xml
  A site for Deep reinforcement learning in Computer Vision 
slogan: Nil        # appears in the header, alongside the title
avatar: /i/avatar_3.png    # appears as portrait in the header
banner: /DRL_in_CV/i/mountains.svg # appears as background in the header
url: http://jekyllrb.com # used by plugins to generate feed.xml and sitemap.xml
baseurl: '/DRL_in_CV/'              # prepended to all absolute filepaths
repo: https://github.com//rlue.github.io # appears in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: Course
    url: /category/course
    icon: /i/icons.svg#posts # icons should be 24x24 px.
  - name: Posts
    url: /category/posts
    icon: /i/icons.svg#portfolio
  - name: Papers 
    url: /DRL_in_CV_Papers/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: About
    url: /about
    icon: /i/icons.svg#portfolio

# Objects listed here will appear on the /projects.html page.


#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }


sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 15
 